server:
  port: 8080
spring:
  application:
    #    注册到注册中心的名称
    name: provider
  datasource:
    url: jdbc:mysql://localhost:3306/qyn?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 837515
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    #    确保找到注册中心的位置
    service-url:
      defaultZone: http://localhost:7776/eureka
mybatis:
  configuration:
    #    mybatis的null的值默认不会封装到map中,这里设置为需要封装，createtime有些为空
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    复杂mapper，xml写入
  mapper-locations: classpath:/mapper/*.xml

